name: Build and Deploy Documentation
on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    DISPLAY: ":99.0"

jobs:
    build-doc:
        name: Build Documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.9
            
            - uses: syphar/restore-virtualenv@v1
              id: cache-virtualenv
              with:
                requirement_files: requirements.txt
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
            
            - name: Build Documentation
              run: |
                make -C doc html
            
            - name: Deploy to GH Pages
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  token: ${{ secrets.ACCESS_TOKEN }}
                  branch: gh-pages
                  folder: doc/build/html
                  clean: true
