name: Build Documentation
on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    DISPLAY: ":99.0"

jobs:
    build-doc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.10
            
            - uses: syphar/restore-virtualenv@v1
              id: cache-virtualenv
              with:
                requirement_files: requirements.txt
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
            
            - name: Build Documentation
              run: |
                make -C doc html SPHINXOPTS="-W --keep-going"
            
            - name: Tar build
              run: tar -czvf doc-build.tar.gz doc/build/
            
            - name: Upload Documentation
              uses: actions/upload-artifact@v2
              with:
                  name: doc-build
                  path: doc-build.tar.gz
    deploy:
        name: Publish Documentation
        runs-on: ubuntu-latest
        needs: build-doc
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4

            - uses: actions/download-artifact@v4
              with:
                name: doc-build
                path: .
            
            - name: UnTar build
              run: tar -xzvf doc-build.tar.gz
            
            - name: Deploy to GH Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./doc/build/html
