name: Build and Deploy Documentation
on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    DISPLAY: ":99.0"

jobs:
    build-doc:
        name: Build Documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.9
            
            - uses: syphar/restore-virtualenv@v1
              id: cache-virtualenv
              with:
                requirement_files: requirements.txt
            
            - name: Install Dependencies for Documentation
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements_doc.txt
            
            - name: Build Documentation
              run: |
                make -C doc html
            
            - name: Deploy to GH Pages
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: doc/build/html
